CREATE TABLE [dbo].[Brand]
(
	[Id] INT NOT NULL  IDENTITY (1,1),
	[CompanyId] INT NOT NULL,
	[LogoFile] NVARCHAR(MAX) NOT NULL,
	[Name] NVARCHAR(20) NOT NULL,
	[MODIFIED_BY] UNIQUEIDENTIFIER NOT NULL, 
	[ValidFrom] datetime2 GENERATED ALWAYS AS ROW START,
	[ValidTo] datetime2 GENERATED ALWAYS AS ROW END,
	PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo),
    CONSTRAINT [PK_Brand_Id] PRIMARY KEY CLUSTERED ([Id] ASC), 
	CONSTRAINT [FK_Brand_Company] FOREIGN KEY ([CompanyId]) REFERENCES [Company]([Id]), 
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[BrandHistory]));
