CREATE TABLE [dbo].[Company]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[Name] NVARCHAR(50) NOT NULL,
	[Address] NVARCHAR(255) NOT NULL,
	[ContactNumber] NVARCHAR(50) NOT NULL,
	[LogoFile] NVARCHAR(MAX) NULL, 
	[MODIFIED_BY] UNIQUEIDENTIFIER NOT NULL,
	[ValidFrom] datetime2 GENERATED ALWAYS AS ROW START,
	[ValidTo] datetime2 GENERATED ALWAYS AS ROW END,
	PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo),
	CONSTRAINT [PK_Company_Id] PRIMARY KEY CLUSTERED ([Id] ASC) 
) 
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[CompanyHistory]));
