CREATE TABLE [dbo].[CustomerVehicleStorageCheckIn]
(
    [Id]                            INT              NOT NULL IDENTITY (1,1),
    [CustomerVehicleId]             INT              NOT NULL,
    [CustomerStorageContractId] INT NOT NULL,
    [VehicleOnChargeImage]          nvarchar(max)    not null,
    [KilometerReadingImage]         nvarchar(max)    not null,
    [VehicleUnderCoverImage]        nvarchar(max)    not null,
    [ParkedTheVehicleOnTireCradles] bit              NOT NULL,
    [ChargerConnected]              bit              NOT NULL,
    [SeatCover]                     bit              NOT NULL,
    [SteeringCover]                 bit              NOT NULL,
    [FloorMats]                     bit              NOT NULL,
    [KeyTagged]                     bit              NOT NULL,
    [KeyPlacedInSafe]               bit              NOT NULL,
    [TimeStamp] DATETIME2 NOT NULL,
    [MODIFIED_BY]                   UNIQUEIDENTIFIER NOT NULL,
    [ValidFrom]                     datetime2 GENERATED ALWAYS AS ROW START,
    [ValidTo]                       datetime2 GENERATED ALWAYS AS ROW END,
    PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo),
    CONSTRAINT [PK_CustomerVehicleStorageCheckIn_Id] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_CustomerVehicleStorageCheckIn_CustomerVehicle] FOREIGN KEY ([CustomerVehicleId]) REFERENCES [CustomerVehicle] ([Id]),
    CONSTRAINT [FK_CustomerVehicleStorageCheckIn_CustomerStorageContract] FOREIGN KEY ([CustomerStorageContractId]) REFERENCES [CustomerStorageContact] ([Id]),
)
    WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[CustomerVehicleStorageCheckInHistory]))