CREATE TABLE [dbo].[ServiceAdvisor]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[Name] NVARCHAR(100) NOT NULL,
	[Address] NVARCHAR(MAX) NOT NULL,
	[ContactNumber] NVARCHAR(50) NOT NULL,
	[CompanyId] INT NOT NULL,
	[MODIFIED_BY] UNIQUEIDENTIFIER NOT NULL,
	[ValidFrom] datetime2 GENERATED ALWAYS AS ROW START,
	[ValidTo] datetime2 GENERATED ALWAYS AS ROW END,
	PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo),
	CONSTRAINT [PK_ServiceAdvisor_Id] PRIMARY KEY CLUSTERED ([Id] ASC), 
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[ServiceAdvisorHistory]));