CREATE TABLE [dbo].[UserRole]
(
	[Id] INT NOT NULL IDENTITY (1,1),
	[RoleId] NVARCHAR (450),
	[UserId] NVARCHAR (450),
	[MODIFIED_BY] UNIQUEIDENTIFIER NOT NULL, 
	[ValidFrom] datetime2 GENERATED ALWAYS AS ROW START,
	[ValidTo] datetime2 GENERATED ALWAYS AS ROW END,
	PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo),
	CONSTRAINT [PK_UserRoles_Id] PRIMARY KEY CLUSTERED ([Id] ASC), 
    CONSTRAINT [FK_UserRoles_Role] FOREIGN KEY ([RoleId]) REFERENCES [Role]([Id]), 
    CONSTRAINT [FK_UserRoles_User] FOREIGN KEY ([UserId]) REFERENCES [User]([Id]), 
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[UserRolesHistory]));